## The determinant of a square matrix can be calculated det() function which also comes from the numpy linalg package. If the determinant is 0, that matrix is not invertible. It is known as a singular matrix in algebra terms.

In [4]:
import numpy as np
a = np.array([[7, 2, 0],
               [1, 9, 1],
               [1, 7, 1]])
print("a = ")
print(a)
det = np.linalg.det(a)
print("\nDeterminant:", np.round(det))

a = 
[[7 2 0]
 [1 9 1]
 [1 7 1]]

Determinant: 14.0
